# Generated by Django 2.2.3 on 2019-07-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='genre_id',
            new_name='genre',
        ),
    ]
