# Generated by Django 2.2.3 on 2019-08-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190801_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='artists', to='core.Artist'),
        ),
    ]
