# Generated by Django 2.2.3 on 2019-08-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190803_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(related_name='songs', to='core.Artist'),
        ),
    ]
