# Generated by Django 3.1.7 on 2021-03-31 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190803_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='bio',
            field=models.TextField(null=True, verbose_name='Artist Bio'),
        ),
        migrations.AddField(
            model_name='artist',
            name='thumbnail',
            field=models.ImageField(default='default.jpeg', upload_to='artists'),
        ),
    ]
