# Generated by Django 3.1.7 on 2021-03-31 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210331_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='thumbnail',
            field=models.ImageField(default='default.png', upload_to='genres'),
        ),
    ]
