# Generated by Django 3.1.7 on 2021-04-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210331_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='youtube_url',
            field=models.TextField(blank=True, null=True, verbose_name='Youtube URL'),
        ),
    ]
