# Generated by Django 3.1.7 on 2021-04-02 11:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_song_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(null=True, upload_to=core.models.song_directory_path),
        ),
    ]
