# Generated by Django 3.1.8 on 2021-04-09 17:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210409_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(max_length=500, upload_to=core.models.song_directory_path),
        ),
    ]
